export const afinitiData1 = {
    heading: "Agile @Afiniti",
    createdBy: "Created by Asli Askan, last modified by Akkentli, Omer on Nov 02, 2021",
    listHeading: "With the right practice and rhythm, we will achieve:",
    dataList: ['Better Planning with One Roadmap : Focusing on what is deliverable in 3 months/ 1 month/ 1 sprint  and what are client/commercial objectives while keeping things transparent, realistic and very well sized.',
        "Successful Sprints, hitting delivery deadlines with Quality: What gets planned, gets delivered with no bugs and no production Incidents. Time saved by avoiding rework on poorly defined and poorly analyzed work.",
        "Efficient resource deployment by rebalancing capacity across teams: A good understanding of future capacity required for the product roadmap, allows HOEs to rebalance their staffing to hit targets.",
        "Performance analysis: A refined understanding on engineering performance with respect to complexity, contribution and hours spent on work done.",
        "Speed & Agility: For being ahead of the competition in the market,  thinking in terms of productivity, rituals, making good use of scrum and lean frameworks should be our north star. "]
}
export const afinitiDataPara2 = {
    dataList: ['It starts with a quarterly roadmap planning meeting. The aim of this meeting is to have a handshake with executives, stakeholders about 3 months roadmap.',
        "It is followed by Quarterly/ Monthly product update meeting to update executives on achievements about quarterly/monthly goals.",
        "The two-week cycle starts with a grooming meeting.",
        "During the Grooming meeting, the team and Product Owner (PO) breaks down the product backlog items into user stories and those user stories need to be doable in max sprint duration.",
        "Sprint starts with a sprint planning meeting. Each sprint must end in 2 (max 4) weeks.",
        "In the sprint planning meeting, PO and the team plan what is going to be done in the upcoming sprint.",
        "Product health check meeting is done biweekly to analyze key metrics or SLOs.",
        "At the end of the sprint, a code walk-through meeting takes place to review and share coding practices so that the team starts to develop a consistent way of coding.",
        "Following code walk-through meeting, sprint review meeting starts, and team demonstrates their finished work to the product owner and stakeholders",
        "Right after the review meeting, the team holds a sprint retrospective meeting to discuss how they have done during the sprint and to identify improvement areas.",
    ]
}

export const sprintTable = [
    {
        th: ["Motion"],
        td: [
            "Sprint Planning"
        ],
        td2: ["Daily"],
        td3: ["Grooming"],
        td4: [
            "Product health check"
        ],
        td5: [
            "Code walk-through"
        ],
        td6: [
            "Sprint Review"
        ],
        td7: [
            "Sprint Retrospective"
        ],
        td8: [
            "Monthly/ Quarterly product update"
        ],
        td9: [
            "Quarterly roadmap planning"
        ]
    },
    {
        th: ["Purpose & Agenda"],
        td: [
            "Come up with items and a goal for upcoming sprint",
            "- Define sprint goal",
            "- Discuss what technical debts items to include in the sprint",
            "- Define (sprint backlog) user stories to deliver at the end of sprint with clear DoD",
            "",
            "Sprint Planning addresses the following topics:",
            "- Topic One: What can be Done this Sprint?",
            "- Topic Two: How will the chosen work get done?",
        ],
        td2: [
            "To share progress, check if they are still on track to successfully complete the sprint, and make a plan for the next day of work",
            "",
            "3 questions:",
            "- What did you do yesterday?",
            "- What will you do today?",
            "- Are there any blockers?"
        ],
        td3: ["Agenda:",
            "- Review of most important user stories for the upcoming two sprints",
            "- Discuss user stories, ask questions to clarify",
            "- Refine bigger stories into smaller ones",
            "- Give estimates (size)",
            "- Answer any related question to smooth out any ambiguity",
            "",
            "Product Owner prepares enough to answer the following questions:",
            "- What are the key themes and stories at the moment?",
            "- Why are these top-priority right now?",
            "- What is their value and how do they match up with our strategic objectives?",
        ],
        td4: [
            "Create a clear visibility about the progress at health check metrics such as",
            "- Service Level Objectives (SLOs)",
            "- Key Results (KRs) or key success metrics",
            "- Customer Related issues ( if there is any)",
            "- Follow-up action items",
        ],
        td5: [
            "Review and share coding practices so that the team starts to develop a consistent way of coding.",
            "",
            "Developers share their code and:",
            "- Get feedback to improve them selves",
            "- Share best practices with team mates",
            "- Ask for opinions",
            "",
            "Agenda:",
            "- Each developer shows the code s/he developed during the sprint in order of importance",
            "- Each developer should have max. 10mins, Every developer must share their work",
        ],
        td6: [
            "During this meeting, the Scrum team shows what they accomplished during the sprint.  The Sprint Review is a working session and the Scrum Team should avoid limiting it to a presentation.",
            "",
            "Team discusses whether the sprint goal is reached",
            "- Team demonstrates their finished work to the product owner and stakeholders",
            "- Team discusses any feedback and business context for this project",
            "- Team updates the product backlog based on the discussion",
        ],
        td7: [
            "1.Inspect how the sprint went in terms of people, relationships, process, and tools.",
            "2.Identify what went well and opportunities for improvement.",
            "3.Create a plan with specific improvements to be carried out during the next sprint.",
            "Although there are different techniques to facilitate a retro meeting, basically the technique of asking following questions to each team member to identify specific things that the team should might be a good start:",
            "1. Start doing",
            "2. Stop doing",
            "3. Continue doing",
        ],
        td8: [
            "Update executives on achievements against quarterly/monthly goals",
            "- Executive summary ( review of the quarter/month)",
            "- Raise flag for top 3 asks beyond plan",
            "- Progress of Quarter's OKRs (red,green,yellow)",
            "- Show top 3 initiatives that shipped",
            "- Risks",
        ],
        td9: [
            "Align executives on the next quarter",
            "- Review product strategy proposal",
            "- Review OKRs for next quarter",
            "- Prioritization of initiatives for the quarter",
        ]
    },
    {
        th: ["Pre-Post work (Deliverable)"],
        td: [
            "Prework:",
            "- PO prioritize the backlog",
            "- PO define sprint goal",
            "",
            "Output:",
            "- Agreed Sprint Goal",
            "- Sprint backlog",
            "",
            "Postwork:",
            "- Development team creates the tasks",
            "- QA team creates the test scenarios"
        ],
        td2: [""],
        td3: [
            "Prework:",
            "PO prepares detailed user stories for grooming with use cases and UI/UX assets",
            "PO defines acceptance criteria",
            "Output:",
            "PO updates user stories with the comments of development team and makes them sprint planning ready with agreed acceptance criteria",
        ],
        td4: [
            "Prework :",
            "- PO will report SLOs progress, KRs, key success metrics.",
            "- PO will bring up critical customer related isssues.",
            "Postwork :",
            "- Action items are defined and assigned to related parties",
        ],
        td5: [
            "Prework :",
            "- Each developer should prioritize their work and think about what they  would like to tell/ask before the meeting",
            "Postwork :",
            "- If a change in the code is needed, a relevant user story or developer task should be added to backlog. PO should be informed.",
            "- If a best practice/standard is decided it should be published. SGA and EA should be informed.",
        ],
        td6: [
            "Prework:",
            "Team prepares demo",
            "",
            "Output:",
            "- Minutes of Meeting",
            "- Sprint Reports for each Scrum Team",
            "- Updated product backlog"
        ],
        td7: [""],
        td8: [""],
        td9: [""],
    },
    {
        th: ["Owner"],
        td: [
            "The Scrum Master facilitates the sprint planning meeting and ensures that meeting rooms are booked, supplies are available, people are prepared, and all video conferencing and other connectivity details are ready to go. In terms of scheduling, the Scrum Master should be time boxing this meeting according to the length of the sprint. The Product Owner is responsible for ensuring that all items in the backlog are prepared before the meeting.",
        ],
        td2: ["Scrum Master"],
        td3: ["PO"],
        td4: [
            "PO",
        ],
        td5: [
            "SGA (If not available SGL)",
        ],
        td6: ["Scrum Master"],
        td7: ["Scrum Master"],
        td8: ["PO"],
        td9: ["PO"],

    },
    {
        th: ["Attendees"],
        td: [
            "- PO",
            "- HoE",
            "- SGLs",
            "- SLs",
            "- Developers",
            "- SDETs/QAs"
        ],
        td2: ["- SM",
            "- SLs",
            "- Developers",
            "- SDETs/QAs"],
        td3: [
            "- PO",
            "- SGLs",
            "- SM",
            "- SLs",
            "- Developers",
            "- SDETs/QAs"
        ],
        td4: [
            "- PO",
            "- SGLs",
            "- HoE",
        ],
        td5: [
            "- Developers",
            "- SDET",
            "- SL",
            "- SGA",
            "- SGL",
        ],
        td6: [
            "- PO",
            "- HoE",
            "- SGLs",
            "- SLs",
            "- Developers",
            "- SDETs/QAs"
        ],
        td7: [
            "- SGL",
            "- SM",
            "- SLs",
            "- Developers",
            "- SDETs/QAs"
        ],
        td8: [
            "C-level",
            "Partnerships",
            "PO",
            "HoE"
        ],
        td9: [
            "C-level",
            "Partnerships",
            "Team",
            "PO",
            "HoE"
        ],
    },
    {
        th: ["Complete in"],
        td: [
            "2-3 Hours",
        ],
        td2: ["15 mins (1 min per developer)"],
        td3: [
            "1 Hour"
        ],
        td4: [
            "1 Hour"
        ],
        td5: [
            "2 Hour"
        ],
        td6: [
            "1 Hour"
        ],
        td7: [
            "1 Hour"
        ],
        td8: [
            "30-60 mins"
        ],

        td9: [
            "3+ Hours"
        ],
    },
];


export const RACITable = [
    {
        th: ["RACI for Roles vs Rituals"],
        td: ["Quarterly Roadmap Planning"],
        td2: ["Clarify client needs, business strategy & Go-to-market"],
        td3:["Develop Quarterly Revenue & Account Development Plan"],
        td4:["Develop Product Objectives & Key Results / Handshake with C-Team"],
        td5:["Populate Technical Debt & Engineering Projects for the Quarter"],
        td6:["Prioritise the EPICs & FRs for Devteam for Quarterly Planning"],
        td7:["Size the Joint Backlog & Establish Engineering Capacity"],
        td8:["Align Rev, GD, Partner. & C-Level Expectations for the Quarter"],
        td9: ["Regular Progress Updates"],
        td10: ["Monthly Product Update - Prepare Summary, OKR goals vs. progress, Wins, Concerns, Problem Teams, What shipped, Plan change asks, customer vision, strategy, objectives etc."],
        td11:["BiWeekly Product Health Check (Availability, Reliability, Releasability, Security, etc.)"],
        td12: ["Backlog Grooming (refinement)"],
        td13: ["Preparing EPICs & FRs (in advance of Grooming)"],
        td14:["Preparing User Stories (in advance of Grooming) (with AC, DOD, and UI/UX assets)"],
        td15:["Coordinating Grooming Meetings for success"],
        td16:["Breaking down stories & creating tasks"],
        td17:["Estimate Work - Sizing (stories)"],
        td18: ["Sprint Planning"],
        td19: ["Keep backlog prioritized before Planning meetings"],
        td20:["Coordinating Planning Meetings for success"],
        td21:["Define Sprint Goal"],
        td22:["Create tasks for Sprint Scope"],
        td23: ["Daily Stand-ups"],
        td24: ["Coordinating Standups for success"],
        td25: ["Sprint Review"],
        td26: ["Prepare Demo"],
        td27:["Review the completion of Epics"],
        td28:["Review the completion of FRs"],
        td29:["Review the completion of Stories/Tasks"],
        td30:["Coordinating Review Meetings for success"],
        td31:["Update backlog based on the discussion"],
        td32: ["Retro" ],
        td33: ["Coordinating Retros for success"]
    },
    {
        th: ["PO"],
        td: ["A"],
        td2: ["A"],
        td3: ["R"],
        td4: ["A/R"],
        td5: [""],
        td6: ["A/R"],
        td7: ["I"],
        td8: ["A/R"],
        td9: ["A Monthly Product Update"], 
        td10: ["A"],
        td11: ["I"],
        td12:["A (for EPICs)"], 
        td13: ["R"], 
        td14: [""],
        td15: ["R (must participate)"],
        td16:[""], 
        td17: [""], 
        td18: ["A ( for defining sprint goal)"],
        td19: ["A"],
        td20:[""], 
        td21: ["A"], 
        td22: [""],
        td23: ["C"],
        td24: [""],
        td25: ["R must participate"],
        td26: [""],
        td27: ["A"],
        td28: ["A"],
        td29: [""],
        td30: ["R must participate"],
        td31: [""],
        td32: [""],
        td33: [""]
    },
    {
        th: ["HoE"],
        td: ["R"],
        td2: ["R"],
        td3: ["C"],
        td4: [""],
        td5: ["R (cascade to teams)"],
        td6: ["A"],
        td7: ["C (support with rough sizing)"],
        td8: ["A"],
        td9: ["R"], 
        td10: ["R"],
        td11: ["A"],
        td12:[""], 
        td13: [""], 
        td14: [""],
        td15: [""],
        td16:[""], 
        td17: [""], 
        td18: [""],
        td19: [""],
        td20:[""], 
        td21: [""], 
        td22: [""],
        td23: [""],
        td24: [""],
        td25: [""],
        td26: [""],
        td27: [""],
        td28: [""],
        td29: [""],
        td30: [""],
        td31: [""],
        td32: [""],
        td33: [""]
    },
    {
        th: ["SGL"],
        td: ["C"],
        td2: ["C"],
        td3: [""],
        td4: [""],
        td5: [""],
        td6: ["R"],
        td7: [""],
        td8: ["R"],
        td9: ["R"], 
        td10: ["R"],
        td11: ["R"],    
        td12:["A( for Stories, Tasks, Estimation)"], 
        td13: [""], 
        td14: ["A"],
        td15: ["R"],
        td16:["A"], 
        td17: ["A"], 
        td18: ["A (for Tasks, Estimation)"],
        td19: [""],
        td20:[""], 
        td21: ["R Tech view"], 
        td22: ["A"],
        td23: ["C"],
        td24: [""],
        td25: ["A Demo"],
        td26: ["A"],
        td27: ["R"],
        td28: ["R"],
        td29: ["A"],
        td30: ["R"],
        td31: ["A"],
        td32: ["R"],
        td33: ["R"]
    },
    {
        th: ["SM"],
        td: [""],
        td2: [""],
        td3: [""],
        td4: [""],
        td5: [""],
        td6: [""],
        td7: [""],
        td8: [""],
        td9: [""], 
        td10: [""],
        td11: [""],
        td12:["C (compliance)"], 
        td13: ["C (compliance)"], 
        td14: ["C (compliance)"], 
        td15: ["A"],
        td16:["C (compliance)"],  
        td17: ["C (compliance)"], 
        td18: ["R (compliance)"], 
        td19: ["R compliance"], 
        td20:["R"], 
        td21: ["R compliance"],  
        td22: ["C (compliance)"],
        td23: ["A"],
        td24: ["A"],
        td25: ["A Coordinate"],
        td26: [""],
        td27: ["C (compliance)"],
        td28: ["C (compliance)"],
        td29: ["C (compliance)"],
        td30: ["A"],
        td31: [""],
        td32: ["A"],
        td33: ["A"]
    },
    {
        th: ["SL"],
        td: [""],
        td2: [""],
        td3: [""],
        td4: [""],
        td5: [""],
        td6: [""],
        td7: [""],
        td8: [""],
        td9: [""], 
        td10: [""],
        td11: [""],
        td12:["R"], 
        td13: [""], 
        td14: ["R"],
        td15: ["R"],
        td16:["R"], 
        td17: ["R"], 
        td18: ["R"],
        td19: [""],
        td20:[""], 
        td21: [""], 
        td22: ["R"],
        td23: ["R"],
        td24: ["R must participate"],
        td25: ["R"],
        td26: ["R"],
        td27: [""],
        td28: [""],
        td29: ["R"],
        td30: ["R"],
        td31: ["R"],
        td32: ["R"],
        td33: ["R"]
    },
    {
        th: ["SDET &QA"],
        td: [""],
        td2: [""],
        td3: [""],
        td4: [""],
        td5: [""],
        td6: [""],
        td7: [""],
        td8: [""],
        td9: [""], 
        td10: [""],
        td11: [""],
        td12:[""], 
        td13: [""], 
        td14: [""],
        td15: [""],
        td16:["I"], 
        td17: [""], 
        td18: ["R (test case prep)"],
        td19: [""],
        td20:[""], 
        td21: [""], 
        td22: ["R (test case prep)"],
        td23: ["R"],
        td24: ["R must participate"],
        td25: [""],
        td26: [""],
        td27: [""],
        td28: [""],
        td29: ["R"],
        td30: [""],
        td31: [""],
        td32: ["R must participate"],
        td33: ["R must participate"]
    },
    {
        th: ["Developers"],
        td: [""],
        td2: [""],
        td3: [""],
        td4: [""],
        td5: [""],
        td6: [""],
        td7: [""],
        td8: [""],
        td9: [""], 
        td10: [""],
        td11: [""],
        td12:[""], 
        td13: [""], 
        td14: [""],
        td15: [""],
        td16:["I"], 
        td17: [""], 
        td18: [""],
        td19: [""],
        td20:[""], 
        td21: [""], 
        td22: ["C"],
        td23: ["R"],
        td24: ["R must participate"],
        td25: [""],
        td26: [""],
        td27: [""],
        td28: [""],
        td29: ["R"],
        td30: ["R must participate"],
        td31: [""],
        td32: ["R must participate"],
        td33: ["R must participate"]
    },
    {
        th: ["ENG OPS"],
        td: ["C"],
        td2: [""],
        td3: [""],
        td4: ["C (compliance)"],
        td5: [""],
        td6: [""],
        td7: [""],
        td8: [""],
        td9: ["C (compliance)"], 
        td10: ["C (compliance)"],
        td11: ["C (compliance)"],
        td12:[""], 
        td13: [""], 
        td14: [""],
        td15: [""],
        td16:[""], 
        td17: [""], 
        td18: [""],
        td19: [""],
        td20:[""], 
        td21: [""], 
        td22: [""],
        td23: [""],
        td24: [""],
        td25: [""],
        td26: [""],
        td27: [""],
        td28: [""],
        td29: [""],
        td30: [""],
        td31: [""],
        td32: [""],
        td33: [""]
    },
]